# Generated by Django 3.2.6 on 2024-04-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20240405_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito_1',
            old_name='Die_Aler_Otro',
            new_name='Dieta/Alergias/Otros',
        ),
        migrations.RenameField(
            model_name='carrito_1',
            old_name='Postres_Extra',
            new_name='Postres/Extras',
        ),
        migrations.AlterField(
            model_name='carrito_1',
            name='Otros',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
