# Generated by Django 3.2.6 on 2024-04-05 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20240405_1009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito_1',
        ),
    ]
