# Generated by Django 3.2.6 on 2024-04-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0006_delete_carrito_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'CARRITO_1',
                'managed': False,
            },
        ),
    ]
