# Generated by Django 3.2.6 on 2024-04-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_carrito1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('General', models.CharField(choices=[('Entero', 'Entero'), ('Entero Hipocalórico', 'Entero Hipocalórico'), ('P+T', 'P+T'), ('UP', 'UP')], max_length=100)),
                ('Dieta/Alergias/Otros', models.CharField(max_length=100)),
                ('Sal', models.BooleanField()),
                ('Postres/Extras', models.CharField(max_length=100)),
                ('Otros', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Carrito1',
        ),
    ]
