# Generated by Django 3.2.6 on 2024-04-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20240405_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito_1',
            name='Postres/Extras',
        ),
        migrations.AddField(
            model_name='carrito_1',
            name='Postres',
            field=models.CharField(choices=[('Yogurt', 'Yogurt'), ('Fruta', 'Fruta'), ('Papilla de fruta', 'Papilla de fruta')], default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='carrito_1',
            name='Dieta/Alergias/Otros',
            field=models.CharField(choices=[('Sin legumbre', 'Sin legumbre'), ('Sin carne', 'Sin carne'), ('Sin pescado', 'Sin pescado'), ('Sin lactosa', 'Sin lactosa')], max_length=100),
        ),
    ]
