# Generated by Django 3.2.6 on 2024-04-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_carrito_1_postres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('General', models.CharField(choices=[('Entero', 'Entero'), ('Entero Hipocalórico', 'Entero Hipocalórico'), ('P+T', 'P+T'), ('UP', 'UP')], max_length=100)),
                ('Dieta/Alergias/Otros', models.CharField(choices=[('Sin legumbre', 'Sin legumbre'), ('Sin carne', 'Sin carne'), ('Sin pescado', 'Sin pescado'), ('Sin lactosa', 'Sin lactosa')], max_length=100)),
                ('Sal', models.BooleanField()),
                ('Postres', models.CharField(choices=[('Yogurt', 'Yogurt'), ('Fruta', 'Fruta'), ('Papilla de fruta', 'Papilla de fruta')], max_length=100)),
                ('Otros', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('General', models.CharField(choices=[('Entero', 'Entero'), ('Entero Hipocalórico', 'Entero Hipocalórico'), ('P+T', 'P+T'), ('UP', 'UP')], max_length=100)),
                ('Dieta/Alergias/Otros', models.CharField(choices=[('Sin legumbre', 'Sin legumbre'), ('Sin carne', 'Sin carne'), ('Sin pescado', 'Sin pescado'), ('Sin lactosa', 'Sin lactosa')], max_length=100)),
                ('Sal', models.BooleanField()),
                ('Postres', models.CharField(choices=[('Yogurt', 'Yogurt'), ('Fruta', 'Fruta'), ('Papilla de fruta', 'Papilla de fruta')], max_length=100)),
                ('Otros', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito_4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('General', models.CharField(choices=[('Entero', 'Entero'), ('Entero Hipocalórico', 'Entero Hipocalórico'), ('P+T', 'P+T'), ('UP', 'UP')], max_length=100)),
                ('Dieta/Alergias/Otros', models.CharField(choices=[('Sin legumbre', 'Sin legumbre'), ('Sin carne', 'Sin carne'), ('Sin pescado', 'Sin pescado'), ('Sin lactosa', 'Sin lactosa')], max_length=100)),
                ('Sal', models.BooleanField()),
                ('Postres', models.CharField(choices=[('Yogurt', 'Yogurt'), ('Fruta', 'Fruta'), ('Papilla de fruta', 'Papilla de fruta')], max_length=100)),
                ('Otros', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito_5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('General', models.CharField(choices=[('Entero', 'Entero'), ('Entero Hipocalórico', 'Entero Hipocalórico'), ('P+T', 'P+T'), ('UP', 'UP')], max_length=100)),
                ('Dieta/Alergias/Otros', models.CharField(choices=[('Sin legumbre', 'Sin legumbre'), ('Sin carne', 'Sin carne'), ('Sin pescado', 'Sin pescado'), ('Sin lactosa', 'Sin lactosa')], max_length=100)),
                ('Sal', models.BooleanField()),
                ('Postres', models.CharField(choices=[('Yogurt', 'Yogurt'), ('Fruta', 'Fruta'), ('Papilla de fruta', 'Papilla de fruta')], max_length=100)),
                ('Otros', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito_6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('General', models.CharField(choices=[('Entero', 'Entero'), ('Entero Hipocalórico', 'Entero Hipocalórico'), ('P+T', 'P+T'), ('UP', 'UP')], max_length=100)),
                ('Dieta/Alergias/Otros', models.CharField(choices=[('Sin legumbre', 'Sin legumbre'), ('Sin carne', 'Sin carne'), ('Sin pescado', 'Sin pescado'), ('Sin lactosa', 'Sin lactosa')], max_length=100)),
                ('Sal', models.BooleanField()),
                ('Postres', models.CharField(choices=[('Yogurt', 'Yogurt'), ('Fruta', 'Fruta'), ('Papilla de fruta', 'Papilla de fruta')], max_length=100)),
                ('Otros', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
