# Generated by Django 3.2.6 on 2024-04-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_carrito_10_carrito_11_carrito_7_carrito_8_carrito_9'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito_10',
            options={},
        ),
    ]
