# Generated by Django 3.2.6 on 2024-04-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_carrito_10_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito_1',
            name='Fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
