# Generated by Django 3.2.6 on 2024-04-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20240408_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito_10',
            old_name='Dieta/Alergias/Otros',
            new_name='Die_Aler_Otro',
        ),
        migrations.RenameField(
            model_name='carrito_11',
            old_name='Dieta/Alergias/Otros',
            new_name='Die_Aler_Otro',
        ),
    ]
