# Generated by Django 3.2.6 on 2024-04-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20240408_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito_1',
            old_name='Dieta/Alergias/Otros',
            new_name='Die_Aler_Otro',
        ),
        migrations.RenameField(
            model_name='carrito_2',
            old_name='Dieta/Alergias/Otros',
            new_name='Die_Aler_Otro',
        ),
        migrations.RenameField(
            model_name='carrito_3',
            old_name='Dieta/Alergias/Otros',
            new_name='Die_Aler_Otro',
        ),
        migrations.RenameField(
            model_name='carrito_4',
            old_name='Dieta/Alergias/Otros',
            new_name='Die_Aler_Otro',
        ),
        migrations.RenameField(
            model_name='carrito_5',
            old_name='Dieta/Alergias/Otros',
            new_name='Die_Aler_Otro',
        ),
        migrations.RenameField(
            model_name='carrito_6',
            old_name='Dieta/Alergias/Otros',
            new_name='Die_Aler_Otro',
        ),
        migrations.RenameField(
            model_name='carrito_7',
            old_name='Dieta/Alergias/Otros',
            new_name='Die_Aler_Otro',
        ),
        migrations.RenameField(
            model_name='carrito_8',
            old_name='Dieta/Alergias/Otros',
            new_name='Die_Aler_Otro',
        ),
        migrations.RenameField(
            model_name='carrito_9',
            old_name='Dieta/Alergias/Otros',
            new_name='Die_Aler_Otro',
        ),
    ]
