# Generated by Django 3.2.6 on 2024-04-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20240408_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito_1',
            name='Numero',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
