# Generated by Django 3.2.6 on 2024-04-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_carrito_1_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito_10',
            name='Numero',
            field=models.IntegerField(default=10, editable=False),
        ),
        migrations.AddField(
            model_name='carrito_11',
            name='Numero',
            field=models.IntegerField(default=11, editable=False),
        ),
        migrations.AddField(
            model_name='carrito_2',
            name='Numero',
            field=models.IntegerField(default=2, editable=False),
        ),
        migrations.AddField(
            model_name='carrito_3',
            name='Numero',
            field=models.IntegerField(default=3, editable=False),
        ),
        migrations.AddField(
            model_name='carrito_4',
            name='Numero',
            field=models.IntegerField(default=4, editable=False),
        ),
        migrations.AddField(
            model_name='carrito_5',
            name='Numero',
            field=models.IntegerField(default=5, editable=False),
        ),
        migrations.AddField(
            model_name='carrito_6',
            name='Numero',
            field=models.IntegerField(default=6, editable=False),
        ),
        migrations.AddField(
            model_name='carrito_7',
            name='Numero',
            field=models.IntegerField(default=7, editable=False),
        ),
        migrations.AddField(
            model_name='carrito_8',
            name='Numero',
            field=models.IntegerField(default=8, editable=False),
        ),
        migrations.AddField(
            model_name='carrito_9',
            name='Numero',
            field=models.IntegerField(default=9, editable=False),
        ),
    ]
