# Generated by Django 3.2.6 on 2024-04-09 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20240408_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito_1',
        ),
        migrations.DeleteModel(
            name='Carrito_10',
        ),
        migrations.DeleteModel(
            name='Carrito_11',
        ),
        migrations.DeleteModel(
            name='Carrito_2',
        ),
        migrations.DeleteModel(
            name='Carrito_3',
        ),
        migrations.DeleteModel(
            name='Carrito_4',
        ),
        migrations.DeleteModel(
            name='Carrito_5',
        ),
        migrations.DeleteModel(
            name='Carrito_6',
        ),
        migrations.DeleteModel(
            name='Carrito_7',
        ),
        migrations.DeleteModel(
            name='Carrito_8',
        ),
        migrations.DeleteModel(
            name='Carrito_9',
        ),
    ]
