# Generated by Django 3.2.6 on 2024-04-09 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0022_auto_20240409_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_carrito', models.IntegerField()),
                ('tipo_comida', models.CharField(choices=[('Entero', 'Entero'), ('Entero Hipocalórico', 'Entero Hipocalórico'), ('P+T', 'P+T'), ('UP', 'UP')], max_length=100)),
                ('dieta_aler_otro', models.CharField(choices=[('Sin legumbre', 'Sin legumbre'), ('Sin carne', 'Sin carne'), ('Sin pescado', 'Sin pescado'), ('Sin lactosa', 'Sin lactosa')], max_length=100)),
                ('sal', models.BooleanField(choices=[(False, 'No'), (True, 'Sí')])),
                ('observaciones', models.TextField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Carrito_9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carrito', models.IntegerField(default=9, editable=False)),
                ('comida', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.comida')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito_8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carrito', models.IntegerField(default=8, editable=False)),
                ('comida', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.comida')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito_7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carrito', models.IntegerField(default=7, editable=False)),
                ('comida', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.comida')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito_6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carrito', models.IntegerField(default=6, editable=False)),
                ('comida', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.comida')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito_5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carrito', models.IntegerField(default=5, editable=False)),
                ('comida', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.comida')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito_4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carrito', models.IntegerField(default=4, editable=False)),
                ('comida', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.comida')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carrito', models.IntegerField(default=3, editable=False)),
                ('comida', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.comida')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carrito', models.IntegerField(default=2, editable=False)),
                ('comida', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.comida')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito_11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carrito', models.IntegerField(default=11, editable=False)),
                ('comida', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.comida')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito_10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carrito', models.IntegerField(default=10, editable=False)),
                ('comida', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.comida')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carrito', models.IntegerField(default=1, editable=False)),
                ('comida', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.comida')),
            ],
        ),
    ]
