# Generated by Django 3.2.6 on 2024-04-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_carrito_1_carrito_10_carrito_11_carrito_2_carrito_3_carrito_4_carrito_5_carrito_6_carrito_7_carrito_'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_postre', models.CharField(choices=[('Yogurt', 'Yogurt'), ('Fruta', 'Fruta'), ('Papilla de fruta', 'Papilla de fruta')], max_length=100)),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
    ]
