# Generated by Django 3.2.6 on 2024-04-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_postre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postre',
        ),
    ]
