# Generated by Django 3.2.6 on 2024-04-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_delete_postre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carrito', models.IntegerField()),
                ('tipo_postre', models.CharField(choices=[('Yogurt', 'Yogurt'), ('Fruta', 'Fruta'), ('Papilla de fruta', 'Papilla de fruta')], max_length=100)),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
    ]
