# Generated by Django 3.2.6 on 2024-04-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_postre'),
    ]

    operations = [
        migrations.AddField(
            model_name='postre',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
